<a href="https://www.kaggle.com/code/subhammudi/09-03-2022-ml-lab-2?scriptVersionId=93357091" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import numpy as np
arr1 = np.empty((2,3))
arr2 = np.array([[10,2,3],[23,45,67]])
print (arr2)
arr3 = np.ones ((2,3))
print (arr3)
Arr4 = np.zeros((2,3),dtype=int)
print (Arr4)

[[10  2  3]
 [23 45 67]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0 0 0]
 [0 0 0]]


In [2]:
np.random.random((2,2))

array([[0.80286572, 0.39922522],
       [0.45292772, 0.19301914]])

In [3]:
var2= np.empty(4)
var2[0] = 5.67
var2[1] =2
var2[2] = 56
var2[3] = 304
print (var2)

[  5.67   2.    56.   304.  ]


In [4]:
print (var2.shape)

(4,)


In [5]:
print (var2.size)

4


In [6]:
var3 = np.empty((2,3))
var3[0][0] = 5.67
var3[0][1] = 2
var3[0][2] = 56
var3[1][0] = .09
var3[1][1] = 132
var3[1][2] = 1056
print(var3)
print(var3.shape)


[[5.670e+00 2.000e+00 5.600e+01]
 [9.000e-02 1.320e+02 1.056e+03]]
(2, 3)


In [7]:
var3 = np.empty((2,3), dtype=int)
var3[0][0] = 5.67
var3[0][1] = 2
var3[0][2] = 56
var3[1][0] = .09
var3[1][1] = 132
var3[1][2] = 1056
print (var3)

[[   5    2   56]
 [   0  132 1056]]


In [8]:
print(var3[1])

[   0  132 1056]


In [9]:
print(var3[[0, 1]])

[[   5    2   56]
 [   0  132 1056]]


In [10]:
print(var3[:, 2])

[  56 1056]


In [11]:
print(var3[1][2])

1056


In [12]:
print(var3[:, [1, 2]])

[[   2   56]
 [ 132 1056]]


In [13]:
print(np.transpose(var3))

[[   5    0]
 [   2  132]
 [  56 1056]]


In [14]:
print(var3.reshape(3,2))

[[   5    2]
 [  56    0]
 [ 132 1056]]


In [15]:
arr4= np.empty((2,3), dtype=int)
arr4[0][0] = 5.67
arr4[0][1] = 2
arr4[0][2] = 56
arr4[1][0] = .09
arr4[1][1] = 132
arr4[1][2] = 1056
print (arr4)

[[   5    2   56]
 [   0  132 1056]]


In [16]:
arr5 = np.empty((1,3), dtype=int)
arr5[0][0] = 37
arr5[0][1] = 2.193
arr5[0][2] = 5609
print (arr5)

[[  37    2 5609]]


In [17]:
arr_concat = np.concatenate((arr4, arr5), axis = 0)
print(arr_concat)

[[   5    2   56]
 [   0  132 1056]
 [  37    2 5609]]


In [18]:
var2.min()

2.0

In [19]:
var2.max()

304.0

In [20]:
var2.cumsum()

array([  5.67,   7.67,  63.67, 367.67])

In [21]:
var2.mean()

91.9175

In [22]:
var2.std()

124.2908299865682